# Etapa de construcción
FROM node:18-alpine as build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build --prod

# Etapa de producción
FROM nginx:1.25-alpine

# Copia los archivos construidos
COPY --from=build /app/dist/administracion-financiera /usr/share/nginx/html

# Configuración de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Puerto expuesto
EXPOSE 80